---
    - name: Install MariaDB server
      yum:
        name: mariadb-server,expect
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
    
    - name: Copy the shell script to the target machine
      copy:
        src: /root/ansible/mysql_secure_installation.sh
        dest: /home/ec2-user/
        mode: '0755'          

    - name: Execute the script
      shell: /home/ec2-user/mysql_secure_installation.sh

    - name: Copy the shell script to the target machine
      copy:
        src: /root/ansible/sql.sh
        dest: /home/ec2-user/
        mode: '0755'

    - name: Execute the script
      shell: /home/ec2-user/sql.sh


